// Generates src/generated/*.ts modules exporting third-party CSS as strings.
// tsdown 0.22 routes .css imports through its css-guard plugin (which wants
// CSS *bundling*), while we need CSS *text* to inject into a shadow root —
// so the strings are materialized as TypeScript ahead of the build.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(rootDir, 'src', 'generated')

/** @type {Array<{ source: string; out: string }>} */
const manifest = [
  { source: 'reveal.js/dist/reset.css', out: 'reveal-reset-css.ts' },
  { source: 'reveal.js/dist/reveal.css', out: 'reveal-css.ts' },
  { source: 'reveal.js/dist/theme/black.css', out: 'theme-black-css.ts' }
]

mkdirSync(outDir, { recursive: true })

for (const { source, out } of manifest) {
  const css = readFileSync(require.resolve(source), 'utf8')
  const module = [
    '// AUTO-GENERATED by scripts/gen-css.mjs — do not edit.',
    `// Source: ${source}`,
    `export default ${JSON.stringify(css)}`,
    ''
  ].join('\n')
  writeFileSync(join(outDir, out), module)
  console.log(`generated src/generated/${out} (${css.length} bytes) from ${source}`)
}
